In [ ]:
import cv2

In [2]:
img = cv2.imread("morgan.jpg",1)
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

In [3]:
print(img)

[[[ 12   0   0]
  [ 12   0   0]
  [ 10   0   0]
  ...
  [ 12   0   0]
  [ 13   1   1]
  [ 14   2   2]]

 [[ 12   0   0]
  [ 12   0   0]
  [ 10   0   0]
  ...
  [ 11   0   0]
  [ 12   0   0]
  [ 12   0   0]]

 [[ 10   0   0]
  [ 10   0   0]
  [ 10   0   0]
  ...
  [ 12   0   0]
  [ 11   0   0]
  [ 11   0   0]]

 ...

 [[ 92  52  53]
  [110  70  71]
  [ 73  33  34]
  ...
  [ 63  11   0]
  [ 61  11   0]
  [ 60  10   0]]

 [[ 57  18  20]
  [ 71  34  36]
  [ 64  27  29]
  ...
  [ 62  10   0]
  [ 62  11   1]
  [ 63  12   2]]

 [[ 54  17  19]
  [ 64  27  29]
  [ 54  20  21]
  ...
  [ 61   9   0]
  [ 62  11   1]
  [ 66  15   5]]]


In [4]:
print(img.shape)

(1440, 1080, 3)


In [5]:
print(type(img))

<class 'numpy.ndarray'>


In [ ]:
import cv2
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.desroyAllWindow(image)

In [ ]:
import cv2

img = cv2.imread("morgan.jpg",1)

resize_img = cv2.resize(img , (600,600))

cv2.imshow("image",resize_img)

cv2.waitKey(0)

cv2.desroyAllWindow(image)

In [ ]:
import cv2

img = cv2.imread("morgan.jpg",1)

resize_img = cv2.resize(img , (int(img.shape[1]/2),int(img.shape[0]/2)))

cv2.imshow("image",resize_img)

cv2.waitKey(0)

cv2.desroyAllWindow(image)

In [ ]:
import cv2

face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

img = cv2.imread("morgan.jpg",1)

gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray_img, scaleFactor=1.05, minNeighbors=5)

print(type(faces))
print(faces)

for x,y,w,h in faces:
    img = cv2.rectangle(img, (x,y), (x+w,y+h), (0,255,0),3)
    
resize_img = cv2.resize(img, (int(img.shape[1]/2), int(img.shape[0]/2)))

cv2.imshow("Gray",resize_img)

cv2.waitKey(0)

cv2.destroyAllWindow(Gray)

<class 'numpy.ndarray'>
[[230 304 773 773]]
