In [1]:
import cv2

In [2]:
img = cv2.imread("morgan.jpg",1)
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

In [3]:
print(img)

[[[ 12   0   0]
  [ 12   0   0]
  [ 10   0   0]
  ...
  [ 12   0   0]
  [ 13   1   1]
  [ 14   2   2]]

 [[ 12   0   0]
  [ 12   0   0]
  [ 10   0   0]
  ...
  [ 11   0   0]
  [ 12   0   0]
  [ 12   0   0]]

 [[ 10   0   0]
  [ 10   0   0]
  [ 10   0   0]
  ...
  [ 12   0   0]
  [ 11   0   0]
  [ 11   0   0]]

 ...

 [[ 92  52  53]
  [110  70  71]
  [ 73  33  34]
  ...
  [ 63  11   0]
  [ 61  11   0]
  [ 60  10   0]]

 [[ 57  18  20]
  [ 71  34  36]
  [ 64  27  29]
  ...
  [ 62  10   0]
  [ 62  11   1]
  [ 63  12   2]]

 [[ 54  17  19]
  [ 64  27  29]
  [ 54  20  21]
  ...
  [ 61   9   0]
  [ 62  11   1]
  [ 66  15   5]]]


In [4]:
print(img.shape)

(1440, 1080, 3)


In [5]:
print(type(img))

<class 'numpy.ndarray'>


In [ ]:
import cv2
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.desroyAllWindow(image)

In [ ]:
import cv2

img = cv2.imread("morgan.jpg",1)

resize_img = cv2.resize(img , (600,600))

cv2.imshow("image",resize_img)

cv2.waitKey(0)

cv2.desroyAllWindow(image)

In [ ]:
import cv2

img = cv2.imread("morgan.jpg",1)

resize_img = cv2.resize(img , (int(img.shape[1]/2),int(img.shape[0]/2)))

cv2.imshow("image",resize_img)

cv2.waitKey(0)

cv2.desroyAllWindow(image)

In [ ]:
import cv2

face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
eyes_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')

img = cv2.imread("morgan.jpg",1)

gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray_img, scaleFactor=1.05, minNeighbors=5)

print(type(faces))
print(faces)

for x,y,w,h in faces:
    img = cv2.rectangle(img, (x,y), (x+w,y+h), (0,255,0),3)

roi_gray = gray_img[y:y+h, x:x+w]
roi_color = img[y:y+h, x:x+w]

eyes = eyes_cascade.detectMultiScale(roi_gray, 1.1, 3)
    
for (ex, ey, ew, eh) in eyes:
    cv2.rectangle(roi_color, (ex,ey), (ex+ew, ey+eh), (0, 255, 0), 2)
    
resize_img = cv2.resize(img, (int(img.shape[1]/2), int(img.shape[0]/2)))

cv2.imshow("Gray",resize_img)

cv2.waitKey(0)

cv2.destroyAllWindow(Gray)

<class 'numpy.ndarray'>
[[230 304 773 773]]


In [ ]:
import cv2

face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

img1 = cv2.imread("morgan.jpg",1)
img2 = cv2.imread("elon.jpg",1)

gray_img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
gray_img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

faces1 = face_cascade.detectMultiScale(gray_img1, scaleFactor=1.05, minNeighbors=5)
faces2 = face_cascade.detectMultiScale(gray_img2, scaleFactor=1.05, minNeighbors=5)

print(type(faces1))
print(faces1)

print(type(faces2))
print(faces2)

for x,y,w,h in faces1:
    img1 = cv2.rectangle(img1, (x,y), (x+w,y+h), (0,255,0),3)
    
for x,y,w,h in faces2:
    img2 = cv2.rectangle(img2, (x,y), (x+w,y+h), (0,255,0),3)
    
resize_img1 = cv2.resize(img1, (int(img1.shape[1]/2), int(img1.shape[0]/2)))
resize_img2 = cv2.resize(img2, (int(img2.shape[1]*2), int(img2.shape[0]*2)))

cv2.imshow("Gray1",resize_img1)
cv2.imshow("Gray2",resize_img2)

cv2.waitKey(0)
cv2.waitKey(0)

cv2.destroyAllWindows()

<class 'numpy.ndarray'>
[[230 304 773 773]]
<class 'numpy.ndarray'>
[[187  84 202 202]]


In [ ]:
import cv2

face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

img = cv2.imread("ian.jpg",1)

gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray_img, scaleFactor=1.05,minNeighbors = 5)

print(type(faces))
print(faces)

for x,y,w,h in faces:
    img = cv2.rectangle(img, (x,y), (x+w,y+h), (0,255,0),3)
    
resize_img = cv2.resize(img, (int(img.shape[1]*2), int(img.shape[0]*2)))

cv2.imshow("Ian",resize_img)

cv2.waitKey(0)

cv2.destroyAllWindow(Originals)

<class 'numpy.ndarray'>
[[ 94  12  64  64]
 [240  57  57  57]
 [421  23  72  72]]
